jobs:
  mvn-compile:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      run: 'cd $GITHUB_WORKSPACE && pwd

        if [ ! -d .git ]; then git init; git config user.email "you@dummy.com"; git
        config user.name "dummy"; git add --all && git commit -q -m "Only fix mvn
        goals for github workflow"; fi

        if [ -f ~/.cskefu.rc ]; then source ~/.cskefu.rc; else echo "Not found ~/.cskefu.rc;
        find info with https://github.com/cskefu/cskefu/issues/688"; exit 1; fi

        java -version && mvn -version

        $GITHUB_WORKSPACE/public/plugins/scripts/install-all.sh

        cd $GITHUB_WORKSPACE/contact-center && ./admin/compile.sh

        '
name: Compile Checks on PRs
on:
  repository_dispatch:
    types: trigger-ga___compile.yml
